[package]
name = "metadata-mashup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
color-eyre = "0.6.3"
futures = "0.3.30"
reqwest = "0.12.7"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
xml2json-rs = "1.0.1"
